name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: gradle
    - uses: gradle/gradle-build-action@v2
    - name: Grant Gradle Permission
      run: chmod +x gradlew
    - name: Setup ForgeGradle
      run: ./gradlew setupCiWorkspace --no-daemon
    - name: Build with Gradle
      run: ./gradlew build --no-daemon
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: SkyblockClient
        path: build/libs/*.jar
